### ISSUE TITLE
Incorrect package description (references camera package)

### ISSUE THREAD

**Issue by jbnunn** [awsdeepracer/aws-deepracer-servo-pkg#2]
The description for the package at https://github.com/aws-deepracer/aws-deepracer-servo-pkg#usage is the same text for that of the camera package and not of the servo package.

> The servo_node provides the core functionality **to combine the camera data from the cameras connected to the USB slots at the front of the AWS DeepRacer vehicle**. Although the node is built to work with the AWS DeepRacer application, you can run it independently for development, testing, and debugging purposes.

**Comment by pratik-nichat** [comment]
Thanks @jbnunn ,
We have updated the README.
